routes/web.php
<?php
use  App\Mail\ContactMessageCreated;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

/* Route::get('/', function () {
    return view('welcome');
})->name('/'); */
Route::get('/', 'WelcomeController@index')->name('/');

Route::get('/home', 'HomeController@index')->name('home');

Route::patch('firstConnect/{id}', 'Auth\LoginController@firstConnect')->name('firstConnect');

Route::post('authenticate', 'Auth\LoginController@authenticate')->name('authenticate');

//Route::get('admin', 'Admin\AdminController@index');

Route::resource('admin/roles', 'Admin\RolesController');

Route::resource('admin/permissions', 'Admin\PermissionsController');

Route::resource('admin/users', 'Admin\UsersController');

//Route::resource('admin/pages', 'Admin\PagesController');

Route::resource('admin/activitylogs', 'Admin\ActivityLogsController')->only([
    'index', 'show', 'destroy'
]);

Route::resource('admin/settings', 'Admin\SettingsController');


Route::middleware('auth')->group(function () {

    Route::get('/formUserPassword', 'Auth\AccountController@formPassword')->name('formMyPassword');

    Route::patch('/changeUserPassword', 'Auth\AccountController@changePassword')->name('changeMyPassword');

    Route::patch('/lockAndUnlockAccount/{id}', 'Auth\AccountController@lockAndUnlock')->name('lockAndUnlockAccount');

    Route::get('reinitialiserMotDePasse/{id}', 'Auth\AccountController@reinitialiserMotDePasse')->name('reinitialiserMotDePasse');

    Route::resource('regions', 'RegionsController');

    Route::resource('provinces', 'ProvincesController');

    Route::resource('communes', 'CommunesController');

    Route::resource('agrements', 'AgrementsController');

    Route::resource('agrements', 'AgrementsController');

    Route::resource('categorieAgrements', 'CategorieAgrementsController');

    Route::resource('categories', 'CategoriesController');

    Route::resource('domaines', 'DomainesController');

    Route::resource('entreprises', 'EntreprisesController');

    Route::resource('statutAgrements', 'StatutAgrementsController');

    Route::resource('statuts', 'StatutsController');

    Route::resource('typeTravauxes', 'TypeTravauxController');

    // My Ajax routes
    Route::get('getCategorie/{domaine?}/{type?}', ['uses' => 'AgrementsController@getCategorie']);

    Route::get('getAgrement/{id?}', ['uses' => 'AgrementsController@getAgrement']);

    Route::get('getEntreprise/{id?}', ['uses' => 'EntreprisesController@getEntreprise']);

    Route::get('getCategoriesByAgrement/{id?}', ['uses' => 'AgrementsController@getCategoriesByAgrement']);

    Route::get('getCommunes/{id?}', ['uses' => 'LocalitesController@getCommunes']);

    Route::get('getProvinces/{id?}', ['uses' => 'LocalitesController@getProvinces']);

    Route::get('getRegions/{id?}', ['uses' => 'LocalitesController@getRegions']);

    Route::get('getAgrementsByEtat/{etat?}', ['uses' => 'AgrementsController@getAgrementsByEtat']);

    Route::post('toggle', ['as' => 'toggle', 'uses' => 'AgrementsController@toggle']);

    Route::post('retirer', ['as' => 'retirer', 'uses' => 'AgrementsController@retirer']);

    Route::resource('rapport', 'RapportController');

    Route::post('resultats', ['as' => 'resultat', 'uses' => 'RapportController@resultats']);

    Route::post('importData', 'AgrementsController@importer')->name('importData');

});

/**************** My defined routes ***************************************/
Route::post('findAgrement', ['as' => 'findAgrement', 'uses' => 'FrontendController@findAgrement']);

Route::post('/contact', 'ContactsController@enregister')->name('contact_path');

Route::post('imprimer', ['as' => 'imprimer', 'uses' => 'FrontendController@export_pdf']);

Route::get('/faq', 'FaqController@recupDonnees')->name('faq_path');

app/Models/CategorieAgrements.php
<?php

namespace App\Models;

use Eloquent as Model;

/**
 * @SWG\Definition(
 *      definition="CategorieAgrements",
 *      required={""},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="Cat_id",
 *          description="Cat_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="Agr_id",
 *          description="Agr_id",
 *          type="integer",
 *          format="int32"
 *      )
 * )
 */
class CategorieAgrements extends Model
{

    public $table = 'CategorieAgrements';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';



    public $fillable = [
        'Cat_id',
        'Agr_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'Cat_id' => 'integer',
        'Agr_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function agr()
    {
        return $this->belongsTo(\App\Models\Agrement::class, 'Agr_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function cat()
    {
        return $this->belongsTo(\App\Models\Category::class, 'Cat_id');
    }
}

app/Http/Controllers/CategorieAgrementsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateCategorieAgrementsRequest;
use App\Http\Requests\UpdateCategorieAgrementsRequest;
use App\Repositories\CategorieAgrementsRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flashy;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class CategorieAgrementsController extends AppBaseController
{
    /** @var  CategorieAgrementsRepository */
    private $categorieAgrementsRepository;

    public function __construct(CategorieAgrementsRepository $categorieAgrementsRepo)
    {
        $this->categorieAgrementsRepository = $categorieAgrementsRepo;
    }

    /**
     * Display a listing of the CategorieAgrements.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->categorieAgrementsRepository->pushCriteria(new RequestCriteria($request));
        $categorieAgrements = $this->categorieAgrementsRepository->all();

        return view('backend.categorie_agrements.index')
            ->with('categorieAgrements', $categorieAgrements);
    }

    /**
     * Show the form for creating a new CategorieAgrements.
     *
     * @return Response
     */
    public function create()
    {
        return view('backend.categorie_agrements.create');
    }

    /**
     * Store a newly created CategorieAgrements in storage.
     *
     * @param CreateCategorieAgrementsRequest $request
     *
     * @return Response
     */
    public function store(CreateCategorieAgrementsRequest $request)
    {
        $input = $request->all();

        $categorieAgrements = $this->categorieAgrementsRepository->create($input);

        Flashy::success('Categorie Agrements enregistré avec succès.');

        return redirect(route('categorieAgrements.index'));
    }

    /**
     * Display the specified CategorieAgrements.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $categorieAgrements = $this->categorieAgrementsRepository->findWithoutFail($id);

        if (empty($categorieAgrements)) {
            Flashy::error('Categorie Agrements non trouvé');

            return redirect(route('categorieAgrements.index'));
        }

        return view('backend.categorie_agrements.show')->with('categorieAgrements', $categorieAgrements);
    }

    /**
     * Show the form for editing the specified CategorieAgrements.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $categorieAgrements = $this->categorieAgrementsRepository->findWithoutFail($id);

        if (empty($categorieAgrements)) {
            Flashy::error('Categorie Agrements non trouvé');

            return redirect(route('categorieAgrements.index'));
        }

        return view('backend.categorie_agrements.edit')->with('categorieAgrements', $categorieAgrements);
    }

    /**
     * Update the specified CategorieAgrements in storage.
     *
     * @param  int              $id
     * @param UpdateCategorieAgrementsRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCategorieAgrementsRequest $request)
    {
        $categorieAgrements = $this->categorieAgrementsRepository->findWithoutFail($id);

        if (empty($categorieAgrements)) {
            Flashy::error('Categorie Agrements non trouvé');

            return redirect(route('categorieAgrements.index'));
        }

        $categorieAgrements = $this->categorieAgrementsRepository->update($request->all(), $id);

        Flashy::success('Categorie Agrements mis à jour avec succès.');

        return redirect(route('categorieAgrements.index'));
    }

    /**
     * Remove the specified CategorieAgrements from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $categorieAgrements = $this->categorieAgrementsRepository->findWithoutFail($id);

        if (empty($categorieAgrements)) {
            Flashy::error('Categorie Agrements non trouvé');

            return redirect(route('categorieAgrements.index'));
        }

        $this->categorieAgrementsRepository->delete($id);

        Flashy::success('Categorie Agrements supprimé avec succès.');

        return redirect(route('categorieAgrements.index'));
    }
}

resources/views/backend/categorie_agrements/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Categorie Agrements
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'categorieAgrements.store']) !!}

                        @include('backend.categorie_agrements.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/categorie_agrements/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Categorie Agrements
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($categorieAgrements, ['route' => ['categorieAgrements.update', $categorieAgrements->id], 'method' => 'patch']) !!}

                        @include('backend.categorie_agrements.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/backend/categorie_agrements/fields.blade.php
<!-- Cat Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('Cat_id', 'Catégorie') !!}
    {!! Form::number('Cat_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Agr Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('Agr_id', 'Agr Id:') !!}
    {!! Form::number('Agr_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Enregistrer', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('categorieAgrements.index') !!}" class="btn btn-default">Annuler</a>
</div>

resources/views/backend/categorie_agrements/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Categorie Agrements</h1>
        <h1 class="pull-right">
           <a class="btn btn-success pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('categorieAgrements.create') !!}">Ajouter</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flashy::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body table-responsive ">
                    @include('backend.categorie_agrements.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/backend/categorie_agrements/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Categorie Agrements
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('backend.categorie_agrements.show_fields')
                    <a href="{!! route('categorieAgrements.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/categorie_agrements/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $categorieAgrements->id !!}</p>
</div>

<!-- Cat Id Field -->
<div class="form-group">
    {!! Form::label('Cat_id', 'Catégorie') !!}
    <p>{!! $categorieAgrements->Cat_id !!}</p>
</div>

<!-- Agr Id Field -->
<div class="form-group">
    {!! Form::label('Agr_id', 'Agr Id:') !!}
    <p>{!! $categorieAgrements->Agr_id !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $categorieAgrements->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $categorieAgrements->updated_at !!}</p>
</div>

resources/views/backend/categorie_agrements/table.blade.php
<table class="table table-responsive" id="categorieAgrements-table">
    <thead>
        <tr>
            <th>Cat Id</th>
        <th>Agr Id</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($categorieAgrements as $categorieAgrements)
        <tr>
            <td>{!! $categorieAgrements->Cat_id !!}</td>
            <td>{!! $categorieAgrements->Agr_id !!}</td>
            <td>
                {!! Form::open(['route' => ['categorieAgrements.destroy', $categorieAgrements->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('categorieAgrements.show', [$categorieAgrements->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('categorieAgrements.edit', [$categorieAgrements->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Êtes-vous sûr ?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>