routes/web.php
<?php
use  App\Mail\ContactMessageCreated;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

/* Route::get('/', function () {
    return view('welcome');
})->name('/'); */
Route::get('/', 'WelcomeController@index')->name('/');

Route::get('/home', 'HomeController@index')->name('home');

Route::patch('firstConnect/{id}', 'Auth\LoginController@firstConnect')->name('firstConnect');

Route::post('authenticate', 'Auth\LoginController@authenticate')->name('authenticate');

//Route::get('admin', 'Admin\AdminController@index');

Route::resource('admin/roles', 'Admin\RolesController');

Route::resource('admin/permissions', 'Admin\PermissionsController');

Route::resource('admin/users', 'Admin\UsersController');

//Route::resource('admin/pages', 'Admin\PagesController');

Route::resource('admin/activitylogs', 'Admin\ActivityLogsController')->only([
    'index', 'show', 'destroy'
]);

Route::resource('admin/settings', 'Admin\SettingsController');


Route::middleware('auth')->group(function () {

    Route::get('/formUserPassword', 'Auth\AccountController@formPassword')->name('formMyPassword');

    Route::patch('/changeUserPassword', 'Auth\AccountController@changePassword')->name('changeMyPassword');

    Route::patch('/lockAndUnlockAccount/{id}', 'Auth\AccountController@lockAndUnlock')->name('lockAndUnlockAccount');

    Route::get('reinitialiserMotDePasse/{id}', 'Auth\AccountController@reinitialiserMotDePasse')->name('reinitialiserMotDePasse');

    Route::resource('regions', 'RegionsController');

    Route::resource('provinces', 'ProvincesController');

    Route::resource('communes', 'CommunesController');

    Route::resource('agrements', 'AgrementsController');

    Route::resource('agrements', 'AgrementsController');

    Route::resource('categorieAgrements', 'CategorieAgrementsController');

    Route::resource('categories', 'CategoriesController');

    Route::resource('domaines', 'DomainesController');

    Route::resource('entreprises', 'EntreprisesController');

    Route::resource('statutAgrements', 'StatutAgrementsController');

    Route::resource('statuts', 'StatutsController');

    Route::resource('typeTravauxes', 'TypeTravauxController');

    // My Ajax routes
    Route::get('getCategorie/{domaine?}/{type?}', ['uses' => 'AgrementsController@getCategorie']);

    Route::get('getAgrement/{id?}', ['uses' => 'AgrementsController@getAgrement']);

    Route::get('getEntreprise/{id?}', ['uses' => 'EntreprisesController@getEntreprise']);

    Route::get('getCategoriesByAgrement/{id?}', ['uses' => 'AgrementsController@getCategoriesByAgrement']);

    Route::get('getCommunes/{id?}', ['uses' => 'LocalitesController@getCommunes']);

    Route::get('getProvinces/{id?}', ['uses' => 'LocalitesController@getProvinces']);

    Route::get('getRegions/{id?}', ['uses' => 'LocalitesController@getRegions']);

    Route::get('getAgrementsByEtat/{etat?}', ['uses' => 'AgrementsController@getAgrementsByEtat']);

    Route::post('toggle', ['as' => 'toggle', 'uses' => 'AgrementsController@toggle']);

    Route::post('retirer', ['as' => 'retirer', 'uses' => 'AgrementsController@retirer']);

    Route::resource('rapport', 'RapportController');

    Route::post('resultats', ['as' => 'resultat', 'uses' => 'RapportController@resultats']);

    Route::post('importData', 'AgrementsController@importer')->name('importData');

});

/**************** My defined routes ***************************************/
Route::post('findAgrement', ['as' => 'findAgrement', 'uses' => 'FrontendController@findAgrement']);

Route::post('/contact', 'ContactsController@enregister')->name('contact_path');

Route::post('imprimer', ['as' => 'imprimer', 'uses' => 'FrontendController@export_pdf']);

Route::get('/faq', 'FaqController@recupDonnees')->name('faq_path');

app/Models/TypeTravaux.php
<?php

namespace App\Models;

use Eloquent as Model;

/**
 * @SWG\Definition(
 *      definition="TypeTravaux",
 *      required={""},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="libelle_type",
 *          description="libelle_type",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="description",
 *          description="description",
 *          type="string"
 *      )
 * )
 */
class TypeTravaux extends Model
{

    public $table = 'TypeTravaux';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';



    public $fillable = [
        'libelle_type',
        'description'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'libelle_type' => 'string',
        'description' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function agrements()
    {
        return $this->hasMany(\App\Models\Agrement::class);
    }
}

app/Http/Controllers/TypeTravauxController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateTypeTravauxRequest;
use App\Http\Requests\UpdateTypeTravauxRequest;
use App\Repositories\TypeTravauxRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flashy;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class TypeTravauxController extends AppBaseController
{
    /** @var  TypeTravauxRepository */
    private $typeTravauxRepository;

    public function __construct(TypeTravauxRepository $typeTravauxRepo)
    {
        $this->typeTravauxRepository = $typeTravauxRepo;
    }

    /**
     * Display a listing of the TypeTravaux.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->typeTravauxRepository->pushCriteria(new RequestCriteria($request));
        $typeTravauxes = $this->typeTravauxRepository->all();

        return view('backend.type_travauxes.index')
            ->with('typeTravauxes', $typeTravauxes);
    }

    /**
     * Show the form for creating a new TypeTravaux.
     *
     * @return Response
     */
    public function create()
    {
        return view('backend.type_travauxes.create');
    }

    /**
     * Store a newly created TypeTravaux in storage.
     *
     * @param CreateTypeTravauxRequest $request
     *
     * @return Response
     */
    public function store(CreateTypeTravauxRequest $request)
    {
        $input = $request->all();

        $typeTravaux = $this->typeTravauxRepository->create($input);

        Flashy::success('Type Travaux enregistré avec succès.');

        return redirect(route('typeTravauxes.index'));
    }

    /**
     * Display the specified TypeTravaux.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $typeTravaux = $this->typeTravauxRepository->findWithoutFail($id);

        if (empty($typeTravaux)) {
            Flashy::error('Type Travaux non trouvé');

            return redirect(route('typeTravauxes.index'));
        }

        return view('backend.type_travauxes.show')->with('typeTravaux', $typeTravaux);
    }

    /**
     * Show the form for editing the specified TypeTravaux.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $typeTravaux = $this->typeTravauxRepository->findWithoutFail($id);

        if (empty($typeTravaux)) {
            Flashy::error('Type Travaux non trouvé');

            return redirect(route('typeTravauxes.index'));
        }

        return view('backend.type_travauxes.edit')->with('typeTravaux', $typeTravaux);
    }

    /**
     * Update the specified TypeTravaux in storage.
     *
     * @param  int              $id
     * @param UpdateTypeTravauxRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateTypeTravauxRequest $request)
    {
        $typeTravaux = $this->typeTravauxRepository->findWithoutFail($id);

        if (empty($typeTravaux)) {
            Flashy::error('Type Travaux non trouvé');

            return redirect(route('typeTravauxes.index'));
        }

        $typeTravaux = $this->typeTravauxRepository->update($request->all(), $id);

        Flashy::success('Type Travaux mis à jour avec succès.');

        return redirect(route('typeTravauxes.index'));
    }

    /**
     * Remove the specified TypeTravaux from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $typeTravaux = $this->typeTravauxRepository->findWithoutFail($id);

        if (empty($typeTravaux)) {
            Flashy::error('Type Travaux non trouvé');

            return redirect(route('typeTravauxes.index'));
        }

        $this->typeTravauxRepository->delete($id);

        Flashy::success('Type Travaux supprimé avec succès.');

        return redirect(route('typeTravauxes.index'));
    }
}

resources/views/backend/type_travauxes/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Type Travaux
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'typeTravauxes.store']) !!}

                        @include('backend.type_travauxes.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/type_travauxes/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Type Travaux
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($typeTravaux, ['route' => ['typeTravauxes.update', $typeTravaux->id], 'method' => 'patch']) !!}

                        @include('backend.type_travauxes.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/backend/type_travauxes/fields.blade.php
<!-- Libelle Type Field -->
<div class="form-group col-sm-6">
    {!! Form::label('libelle_type', 'Libelle Type:') !!}
    {!! Form::text('libelle_type', null, ['class' => 'form-control']) !!}
</div>

<!-- Description Field -->
<div class="form-group col-sm-6">
    {!! Form::label('description', 'Description:') !!}
    {!! Form::text('description', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Enregistrer', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('typeTravauxes.index') !!}" class="btn btn-default">Annuler</a>
</div>

resources/views/backend/type_travauxes/index.blade.php
@extends('layouts.app')
@section('title')
Type de travaux
@endsection
@section('content')
    <section class="content-header">
        <h1 class="pull-left">Type Travaux</h1>
        <h1 class="pull-right">
           <a class="btn btn-success pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('typeTravauxes.create') !!}">Ajouter</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flashy::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body table-responsive ">
                    @include('backend.type_travauxes.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/backend/type_travauxes/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Type Travaux
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('backend.type_travauxes.show_fields')
                    <a href="{!! route('typeTravauxes.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/type_travauxes/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $typeTravaux->id !!}</p>
</div>

<!-- Libelle Type Field -->
<div class="form-group">
    {!! Form::label('libelle_type', 'Libelle Type:') !!}
    <p>{!! $typeTravaux->libelle_type !!}</p>
</div>

<!-- Description Field -->
<div class="form-group">
    {!! Form::label('description', 'Description:') !!}
    <p>{!! $typeTravaux->description !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $typeTravaux->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $typeTravaux->updated_at !!}</p>
</div>

resources/views/backend/type_travauxes/table.blade.php
<table class="table table-responsive" id="tabl">
    <thead>
        <tr>
            <th>Libelle Type</th>
        <th>Description</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($typeTravauxes as $typeTravaux)
        <tr>
            <td>{!! $typeTravaux->libelle_type !!}</td>
            <td>{!! $typeTravaux->description !!}</td>
            <td>
                {!! Form::open(['route' => ['typeTravauxes.destroy', $typeTravaux->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('typeTravauxes.show', [$typeTravaux->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('typeTravauxes.edit', [$typeTravaux->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Êtes-vous sûr ?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>